# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SLDS 2020"
email: "statisticallearninganddatasci@gmail.com"
description: "Conference on Statistical Learning and Data Science/Nonparametric Statistics 2020"
baseurl: "/SLDS2020"
url: "https://asaslds.github.io/SLDS2020/"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "ASA SLDS"
organizerAlternateName: "ASA Section on Statistical Learning and Data Science"
organizerDescription: "ASA SLDS serves as ASA's focal point for Statistical Learning and Data Science issues; build cooperative relationships on behalf of the Association with other organizations that have interests in these fields; encourage the use of Statistical Learning methods in Data Science applications; create forums for presentation and discussion of research in these fields"
organizerEmail: "statisticallearninganddatasci@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://community.amstat.org/slds/home"

# Head
metaKeywords: "ASA, SLDS, Statistics, Data Science, Irvine"
#twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/563fdbcjrNm4Lge26"
c4sponsorsUrl: "/assets/SLDS_2020_Sponsors.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "Program Committee"}
 - {permalink: "/courses/", text: "Invited Short Courses"}
 - {permalink: "/registration/", text: "Registration & Key Dates"}
 - {link: "https://publish.illinois.edu/sldsc2018/", text: "SLDS 2018"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Program Outline"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Invited Session Proposals Submission"}
rightNavigationButtons:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Invited Session Proposals Submission"}

# Hero Block
heroImage: "Irvine.jpg"
heroTitle: "SLDS 2020 <typeout>"
eventDate: "May 27-29, 2020"
typeoutTextValues: '"", "Statistics", "DataScience", "NonparaStat", "UC-Irvine"'
typeoutFallback: "UC-Irvine"
heroButtons:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Be on the Program"}
 - {permalink: "/#about", text: "Conference Info"}

# About Block
aboutTitle: "SLDS 2020"
aboutBlock:
 - {title: "Conference", image: "conference.JPG", text: "Conference on Statistical Learning and Data Science/Nonparametric Statistics 2020 (SLDS 2020)-- a bi-annual gathering of top researchers in Statistical Learning, Data Science, and Nonparametric Statistics, and a forum for presentation and discussion of research."}
 - {title: "Short Courses", image: "shortcourse.JPG", text: "Learning opportunities on the latest advances in data science. ASA SLDS encourages the use of Statistical Learning methods in Data Science applications."}
 - {title: "Networking", image: "networking.JPG", text: "A platform to promote young researchers and graduate students. ASA SLDS builds cooperative relationships on behalf of the Association with other organizations that have interests in these fields."}

# Statistic Block
statisticBlockImage: "poster.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "45", specialCharacter: "+", info: "sessions", detail: "state-of-the-art in data science"}
 - {count: "20", specialCharacter: "+", info: "posters", detail: "with travel support from NSF"}
 - {count: "3", specialCharacter: "", info: "keynotes", detail: "envision the future of statistics"}

# Team Block
teamBlockTitle: "Program Committee"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Rockstar Speakers Block
rockstarSpeakersImage: "slds2018.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Keynote Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationImage: "hyatt.jpg"
locationBlockTitle: "Conference Venue"
eventLocationName: "Hyatt Regency Newport Beach"
eventLocationLink: "https://www.hyatt.com/en-US/hotel/california/hyatt-regency-newport-beach/"
eventStreetAddress: "1107 Jamboree Road"
eventAddressLocality: "Newport Beach"
eventAddressLocalityRegion: "California"
eventPostalCode: "92660"
eventAddressCountry: "United States"
eventStartTime: "2020-05-27T08:00"
#eventDoorTime: "09:00"
eventEndTime: "2020-05-29T16:00"
eventPlaceCoordinates: "33.6177875,-117.8887242"
mapCenterCoordinates: "33.6177875,-117.8887242"
mapMobileCenterCoordinates: "33.6177875,-117.8887242"

# Invited Short Courses
shortCourseTitle: "Invited Short Courses"
aboutShortCourseTitle: "Invited Short Courses"
shortCourseRows: 
 - {title: "Short Course I (SC1) | Deep Learning in Statistics",
    image: "qu_wang_dobriban2.png",
    instructors: "Annie Qu (UIUC), Xiao Wang (Purdue University), Edgar Dobriban (University of Pennsylvania)",
    time: "Tuesday, May 26, 2020, 9 AM - 5 PM",
    cost: "100",
    details: "This short course is for those new to data science and interested in understanding the cutting-edge deep learning models. It is for those who want to become familiar with the core concepts behind deep learning algorithms and their successful applications. It is for those who want to start thinking about how deep learning might be useful in their business or career. This one-day short course will provide a comprehensive overview of deep learning methods from the statistics perspective. Topics include deep feedforward neural networks, convolutional neural networks, deep Boltzmann machine, variational autoencoders, generative adversarial networks, learning theory fundamentals, generalization error bounds for deep neural networks, deep learning in R, an overview of the Keras package. Various application examples will be discussed in detail as well."}
 - {title: "Short Course II (SC2) | Artificial Intelligence, Machine Learning, and Precision Medicine",
    image: "haoda_fu.jpg",
    instructors: "Haoda Fu (Eli Lilly)",
    time: "Tuesday, May 26, 2020, 1 PM - 5 PM",
    cost: "50",
    details: "This half-day short course will provide an overview of statistical machine learning, and artificial intelligence techniques with applications to the precision medicine, in particular, to deriving optimal individualized treatment strategies for personalized medicine. This short course will cover both the treatment selection and treatment transition. The treatment selection framework is based on outcome weighted classification. We will cover logistic regression, support vector machine (SVM), ?-learning, robust SVM, and angle based classifiers for multi-category learning, and we will show how to modify these classification methods into outcome weighted learning algorithms for personalized medicine. The second part of this short course will also cover the treatment transition. We will provide an introduction to reinforcement learning techniques. Algorithms, including dynamic programming for Markov Decision Process, temporal difference learning, SARSA, Q-Learning algorithms, actor-critic methods, will be covered. We will discuss how to use these methods for developing optimal treatment transition strategies. The techniques discussed will be demonstrated in R. This course is intended for graduate students who have some knowledge of statistics and want to be introduced to statistical machine learning, or practitioners who would like to apply statistical machine learning techniques to their problems on personalized medicine and other biomedical applications."}
instructorBios:
 - {name: 'Annie Qu',
    affiliation: 'University of Illinois Urbana Champaign',
    email: 'anniequ@illinois.edu',
    bio: 'Annie Qu is Data Science Founder Professor of Statistics at the University of Illinois at Urbana-Champaign. She received her Ph.D. in Statistics from Penn State in 1998. Her research interests include machine learning, medical imaging, recommender system, natural language processing, personalized medicine, longitudinal/correlated data analysis, missing data, model selection and nonparametric models. Dr. Qu received an NSF Career award, and is a fellow of the Institute of Mathematical Statistics and of the American Statistical Association. She is the past Chair of the Statistics Learning and Data Science Section of the American Statistical Association. Currently, she is associate editor for JASA, Electronic Journal of Statistics and Journal of Nonparametric Statistics. She also served as associate editor for Biometrics and Statistical Science in the past.'}
 - {name: 'Xiao Wang',
    affiliation: 'Purdue University',
    email: 'wangxiao@purdue.edu',
    bio: 'Xiao Wang obtained his B.S. and M.S. in mathematics from University of Science and Technology of China, and Ph.D. in Statistics from University of Michigan. He is now a Professor in Department of Statistics at Purdue University. His research interests are primiarly on machine learning, deep learning, nonparametric statistics, functional data analysis, and reliability, as well as their application in neuroimage, bioinformatics, and industry. He also serves as associate editor of Journal of the American Statistical Association, Technometrics, and Lifetime Data Analysis.'}
 - {name: 'Edgar Dobriban',
    affiliation: 'University of Pennsylvania',
    email: 'dobriban@wharton.upenn.edu',
    bio: 'Edgar Dobriban holds a B.A. in mathematics from Princeton University (with highest honors) and a Ph.D. degree in Statistics from Stanford University. He is currently an Assistant Professor of Statistics in the Wharton School of the University of Pennsylvania. His research interests include the statistical analysis of massive datasets, applications of random matrix theory, distributed statistical learning and deep learning. His work has been published in leading journals in statistics, such as the Annals of Statistics, Annals of Applied Statistics, Journal of the Royal Statistical Society, Biometrika. He has developed publicly available software for processing big data using tools from random matrix theory. He received the TW Anderson Prize for best PhD thesis in the theory of statistics from Stanford University in 2017.'}
 - {name: 'Haoda Fu',
    affiliation: 'Eli Lilly',
    bio: 'Dr. Haoda Fu is a research fellow and a enterprise lead for Machine Learning, Artificial Intelligence, and Digital Connected Care from Eli Lilly and Company. Dr. Haoda Fu is a Fellow of ASA (American Statistical Association). He is also an adjunct professor of biostatistics department, Indiana university school of medicine. Dr. Fu received his Ph.D. in statistics from University of Wisconsin - Madison in 2007 and joined Lilly after that. Since he joined Lilly, he is very active in statistics methodology research. He has more than 90 publications in the areas, such as Bayesian adaptive design, survival analysis, recurrent event modeling, personalized medicine, indirect and mixed treatment comparison, joint modeling, Bayesian decision making, and rare events analysis. In recent years, his research area focuses on machine learning and artificial intelligence. His research has been published in various top journals including JASA, JRSS, Biometrics, ACM, IEEE, JAMA, Annals of Internal Medicine etc.. He has been teaching topics of machine learning and AI in large industry conferences including teaching this topic in FDA workshop. He was board of directors for statistics organizations and program chairs, committee chairs such as ICSA, ENAR, and ASA Biopharm session.'}

# Registration Page
keyDates:
- {date: 'February 15th, 2020',
   info: 'Deadline for Contributed Poster Submissions, Student Paper Competition Submissions, and Student Travel Award Applications'}
- {date: 'April 15th, 2020',
   info: 'Early Registration Ends'}
- {date: 'May 5th, 2020',
   info: 'Hotel Reservation Ends'}
- {date: 'May 15th, 2020',
   info: 'Registration Cancellation Deadline'}
registrationTitles:
   - 'Member Type'
   - 'Now through April 15, 2020'
   - 'After April 15, 2020'
registrationCost:
- {rowLabel: 'Nonmember',
   earlyCost: 500,
   lateCost: 600}
- {rowLabel: 'NPAR Section Member',
   earlyCost: 400,
   lateCost: 500}
- {rowLabel: 'SLDS Section Member',
   earlyCost: 400,
   lateCost: 500}
- {rowLabel: 'Student, ASA Member',
   earlyCost: 200,
   lateCost: 300}
- {rowLabel: 'Student, Non-ASA Member',
   earlyCost: 300,
   lateCost: 400}
- {rowLabel: 'Senior (age â‰¥ 65)',
   earlyCost: 200,
   lateCost: 300}

# Posters Page
posterSubmitLink: '#'
contributedPostersDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

# Poster Prizes Block
posterPrizesTitle: "Poster Awards"
posterPrizesText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

# Poster Paper Submission Text
paperCompetitionTitle: "Student Paper Competition"
paperCompetitionText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

# Travel Award Info
travelAwardInfoTitle: "Travel Award Information"
travelAwardInfoText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."