# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SLDS 2020"
email: "statisticallearninganddatasci@gmail.com"
description: "Conference on Statistical Learning and Data Science/Nonparametric Statistics 2020"
baseurl: "/SLDS2020"
url: "https://asaslds.github.io/SLDS2020/"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "ASA SLDS"
organizerAlternateName: "ASA Section on Statistical Learning and Data Science"
organizerDescription: "ASA SLDS serves as ASA's focal point for Statistical Learning and Data Science issues; build cooperative relationships on behalf of the Association with other organizations that have interests in these fields; encourage the use of Statistical Learning methods in Data Science applications; create forums for presentation and discussion of research in these fields"
organizerEmail: "statisticallearninganddatasci@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://community.amstat.org/slds/home"

# Head
metaKeywords: "ASA, SLDS, Statistics, Data Science, Irvine"
#twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/563fdbcjrNm4Lge26"
c4sponsorsUrl: "/assets/SLDS_2020_Sponsors.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "Program Committee"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Program Outline"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Invited Session Proposals Submission"}
rightNavigationButtons:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Invited Session Proposals Submission"}

# Hero Block
heroImage: "Irvine.jpg"
heroTitle: "SLDS 2020 <typeout>"
eventDate: "May 27-29, 2020"
typeoutTextValues: '"", "Statistics", "DataScience", "NonparaStat", "UC-Irvine"'
typeoutFallback: "UC-Irvine"
heroButtons:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Be on the Program"}
 - {permalink: "/#about", text: "Conference Info"}

# About Block
aboutTitle: "SLDS 2020"
aboutBlock:
 - {title: "Conference", image: "conference.JPG", text: "Conference on Statistical Learning and Data Science/Nonparametric Statistics 2020 (SLDS 2020)-- a bi-annual gathering of top researchers in Statistical Learning, Data Science, and Nonparametric Statistics, and a forum for presentation and discussion of research."}
 - {title: "Short Courses", image: "shortcourse.JPG", text: "Learning opportunities on the latest advances in data science. ASA SLDS encourages the use of Statistical Learning methods in Data Science applications."}
 - {title: "Networking", image: "networking.JPG", text: "A platform to promote young researchers and graduate students. ASA SLDS builds cooperative relationships on behalf of the Association with other organizations that have interests in these fields."}

# Statistic Block
statisticBlockImage: "SLDS2018.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "45", specialCharacter: "+", info: "sessions", detail: "state-of-the-art in data science"}
 - {count: "20", specialCharacter: "+", info: "posters", detail: "with travel support from NSF"}
 - {count: "3", specialCharacter: "", info: "keynotes", detail: "envision the future of statistics"}
 - {count: "2", specialCharacter: "", info: "short courses", detail: "learning opportunities"}
 - {count: "3", specialCharacter: "", info: "student paper winners", detail: "best of the next generation"}

# Team Block
teamBlockTitle: "Program Committee"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Keynote Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationImage: "hyatt.jpg"
locationBlockTitle: "Conference Venue"
eventLocationName: "Hyatt Regency Newport Beach"
eventLocationLink: "https://www.hyatt.com/en-US/hotel/california/hyatt-regency-newport-beach/"
eventStreetAddress: "1107 Jamboree Road"
eventAddressLocality: "Newport Beach"
eventAddressLocalityRegion: "California"
eventPostalCode: "92660"
eventAddressCountry: "United States"
eventStartTime: "2020-05-27T08:00"
#eventDoorTime: "09:00"
eventEndTime: "2020-05-29T16:00"
eventPlaceCoordinates: "33.6177875,-117.8887242"
mapCenterCoordinates: "33.6177875,-117.8887242"
mapMobileCenterCoordinates: "33.6177875,-117.8887242"
