# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SLDS 2020"
email: "statisticallearninganddatasci@gmail.com"
description: "Conference on Statistical Learning and Data Science/Nonparametric Statistics 2020"
baseurl: "/SLDS2020"
url: "https://asaslds.github.io/SLDS2020/"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "ASA SLDS"
organizerAlternateName: "ASA Section on Statistical Learning and Data Science"
organizerDescription: "ASA SLDS serves as ASA's focal point for Statistical Learning and Data Science issues; build cooperative relationships on behalf of the Association with other organizations that have interests in these fields; encourage the use of Statistical Learning methods in Data Science applications; create forums for presentation and discussion of research in these fields"
organizerEmail: "statisticallearninganddatasci@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://community.amstat.org/slds/home"

# Head
metaKeywords: "ASA, SLDS, Statistics, Data Science, Irvine"
#twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/563fdbcjrNm4Lge26"
c4sponsorsUrl: "/assets/SLDS_2020_Sponsors.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "Program Committee"}
 - {link: "https://publish.illinois.edu/sldsc2018/", text: "SLDS 2018"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Program Outline"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Invited Session Proposals Submission"}
rightNavigationButtons:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Invited Session Proposals Submission"}

# Hero Block
heroImage: "Irvine.jpg"
heroTitle: "SLDS 2020 <typeout>"
eventDate: "May 27-29, 2020"
typeoutTextValues: '"", "Statistics", "DataScience", "NonparaStat", "UC-Irvine"'
typeoutFallback: "UC-Irvine"
heroButtons:
 - {link: "https://forms.gle/563fdbcjrNm4Lge26", text: "Be on the Program"}
 - {permalink: "/#about", text: "Conference Info"}

# About Block
aboutTitle: "SLDS 2020"
aboutBlock:
 - {title: "Conference", image: "conference.JPG", text: "Conference on Statistical Learning and Data Science/Nonparametric Statistics 2020 (SLDS 2020)-- a bi-annual gathering of top researchers in Statistical Learning, Data Science, and Nonparametric Statistics, and a forum for presentation and discussion of research."}
 - {title: "Short Courses", image: "shortcourse.JPG", text: "Learning opportunities on the latest advances in data science. ASA SLDS encourages the use of Statistical Learning methods in Data Science applications."}
 - {title: "Networking", image: "networking.JPG", text: "A platform to promote young researchers and graduate students. ASA SLDS builds cooperative relationships on behalf of the Association with other organizations that have interests in these fields."}

# Statistic Block
statisticBlockImage: "poster.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "45", specialCharacter: "+", info: "sessions", detail: "state-of-the-art in data science"}
 - {count: "20", specialCharacter: "+", info: "posters", detail: "with travel support from NSF"}
 - {count: "3", specialCharacter: "", info: "keynotes", detail: "envision the future of statistics"}

# Team Block
teamBlockTitle: "Program Committee"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Rockstar Speakers Block
rockstarSpeakersImage: "slds2018.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Keynote Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationImage: "hyatt.jpg"
locationBlockTitle: "Conference Venue"
eventLocationName: "Hyatt Regency Newport Beach"
eventLocationLink: "https://www.hyatt.com/en-US/hotel/california/hyatt-regency-newport-beach/"
eventStreetAddress: "1107 Jamboree Road"
eventAddressLocality: "Newport Beach"
eventAddressLocalityRegion: "California"
eventPostalCode: "92660"
eventAddressCountry: "United States"
eventStartTime: "2020-05-27T08:00"
#eventDoorTime: "09:00"
eventEndTime: "2020-05-29T16:00"
eventPlaceCoordinates: "33.6177875,-117.8887242"
mapCenterCoordinates: "33.6177875,-117.8887242"
mapMobileCenterCoordinates: "33.6177875,-117.8887242"

# Invited Short Courses
aboutHackathonTitle: "Meet our themes"
hackathonRows: 
 - {title: "Short Course I (SC1) | Deep Learning in Statistics",
    image: "hackathon-0.png",
    instructors: "Annie Qu (anniequ@illinois.edu, UIUC), Xiao Wang (wangxiao@purdue.edu, Purdue University), Edgar Dobriban (dobriban@wharton.upenn.edu, University of Pennsylvania)",
    time: "Tuesday, May 26, 2020, 9 AM - 5 PM",
    cost: "Cost: $100. Seats are limited. One may add this short course to his/her registration at any time via the registration form (link to the registration page).",
    details: "This short course is for those new to data science and interested in understanding the cutting-edge deep learning models. It is for those who want to become familiar with the core concepts behind deep learning algorithms and their successful applications. It is for those who want to start thinking about how deep learning might be useful in their business or career. This one-day short course will provide a comprehensive overview of deep learning methods from the statistics perspective. Topics include deep feedforward neural networks, convolutional neural networks, deep Boltzmann machine, variational autoencoders, generative adversarial networks, learning theory fundamentals, generalization error bounds for deep neural networks, deep learning in R, an overview of the Keras package. Various application examples will be discussed in detail as well."}


# # Hackathon
# hackathonTitle: "Hackathon"
# enableHackathon: true

# # Hackathon About Block
# aboutHackathonTitle: "Meet our themes"
# hackathonRows:
#  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
#  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
#  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# # Hackathon Judges Block
# judgesImage: "judges.jpg"
# judgesTitle: "Judges"

# # Hackathon Prizes Block
# prizesTitle: "Prizes"
# prizes:
#  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
#  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
#  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

